name: Application Spring Boot


on:
    push:
        branches: [master]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Java
              uses: actions/setup-java@v3
              with: 
                distribution: 'temurin'
                java-version: '17'
            - name: Build project
              run: mvn clean install -DskipTests
            - name: Login docker
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t danieleleaoe/events-springboot .
            - name: Publish image to docker hub
              run: docker push danieleleaoe/events-springboot

    deploy: 
        needs: build
        runs-on: self-hosted
        steps:
          - name: Pull image from docker hub
            run: docker pull danieleleaoe/events-springboot:latest
          - name: Remove container
            run: docker rm -f events-springboot
          - name: Run docker container
            run: docker run -d -p 8080:8080  -e  DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PWD=${{secrets.DATABASE_PWD}} --name events-springboot danieleleaoe/events-springboot
            
